dataset:
  name: iris # diabetes

plotter:
  name: tree
  directory: "../plots/"

model:
  type: classifier # regressor

  hyperparameter_classifier:
        criterion: gini
        splitter: best
        max_depth: 100
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: sqrt
        random_state: 13
        max_leaf_nodes: 100
        min_impurity_decrease: 0.0
        class_weight: balanced
        ccp_alpha: 0.0

  hyperparameter_regressor:
    n_estimators: 100
    criterion: absolute_error
    splitter: best
    max_depth: 100
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: sqrt
    random_state: 13
    max_leaf_nodes: 100
    min_impurity_decrease: 0.0
    class_weight: balanced
    ccp_alpha: 0.0
